## id false为绝对位置起飞，x y z绝对起飞位置，true为相对位置起飞，h相对起飞高度
take_off:
  id: true
  x: 0.0
  y: 0.0
  z: 5.0
  h: 5.0

## 返航位置
home:
  x: 0.0
  y: 0.0
  z: 5.0

## 降落位置
landing:
  x: 0.0
  y: 0.0
  vz: -0.5 #降落速度

## 到点范围
range:
  x: 0.1
  y: 0.1
  z: 0.1